# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'Hosted Windows 2019 with VS2019'
  vmImage: ubuntu-latest

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '17.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install -g @angular/cli
#     npm install
#     ng build --prod
#   displayName: 'npm install and build'


  
# - task: JavaToolInstaller@0
#   inputs:
#     versionSpec: '11'
#     jdkArchitectureOption: 'x64'
#     jdkSourceOption: 'PreInstalled'
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'spring-boot-ecommerce/pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '11'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)'
#     ArtifactName: 'webapp'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '26.0.0'


- task: Docker@2
  inputs:
    
    Dockerfile: 'Dockerfile' 
    command: 'buildAndPush'
    containerRegistry: 'dockerecomm'
    tags: '$(Build.BuildId)'

  # env:
  #   DOCKER_BUILD_VERBOSE: '1'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Azure subscription 1 (2c72b524-e7f4-4285-8666-6cbe2a5b7603)'
#     appType: 'webApp'
#     appName: 'shopycart-app'
#     package: '$(System.DefaultWorkingDirectory)/_vidhya-jeeva.AngularFront(11)'
#     deploymentMethod: 'auto'
#     appSettings: |
#       WEBSITE_RUN_FROM_PACKAGE=1
# - task: DockerInstaller@0
#   inputs:
#     dockerVersion: '20.10.10'
# - task: Docker@2
#   inputs:
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
# - task: Docker@2
#   inputs:
#     containerRegistry: 'dockerecomm'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
#     arguments: '--verbose'

